; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description  = Gateway Lab V1 - Découverte et inventaire des appareils sur le réseau local
default_envs = esp32s3_n16r8

[env:esp32s3_n16r8]
platform      = espressif32
board         = esp32-s3-devkitc-1-n16r8v
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600

board_build.usb_mode        = "cdc"
board_build.usb_cdc_on_boot = 1
board_build.filesystem      = littlefs

; Phase de développement :
; Exécuter manuellement : python tools/minify_web.py
; Les fichiers générés sont versionnés dans Git.
; Aucun pre-script n'est requis pendant le développement actif.
;
; Lorsque la structure du projet sera stabilisée :
; Décommenter la ligne suivante pour automatiser la génération
; des assets web avant chaque compilation.
;
; extra_scripts = pre:tools/custom_hooks.py


build_unflags =
    -std=gnu++11
    -std=gnu++14

build_flags =
    -std=gnu++17
    -D PROJECT_VERSION='"0.3.0"'
    -D PROJECT_NAME='"GatewayLabV1"'
    -D TARGET_ESP32_S3

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
