#!/usr/bin/env python3
"""
Web Assets Minifier — Gateway Lab V1

Génère les headers C++ depuis les sources :
  HTML  : web_src/*.html  →  include/web_interface*.h  (PROGMEM)
  OUI   : data/oui.json   →  include/oui_table.h       (OUI_TABLE[])

Workflow :
  1. Modifier web_src/*.html ou data/oui.json
  2. Exécuter : python tools/minify_web.py
  3. Les headers générés sont versionnés dans Git
  4. Compiler normalement : pio run

Requirements (optionnels — fallback intégré) :
    pip install rcssmin rjsmin
"""

import json
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Chemins
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_SRC_DIR  = PROJECT_ROOT / "web_src"
DATA_DIR     = PROJECT_ROOT / "data"
INCLUDE_DIR  = PROJECT_ROOT / "include"

# ---------------------------------------------------------------------------
# Pages HTML à traiter : (source, header_dest, const_name, data_copy|None)
# ---------------------------------------------------------------------------
PAGES = [
    (
        WEB_SRC_DIR / "index.html",
        INCLUDE_DIR / "web_interface.h",
        "INDEX_HTML",
        DATA_DIR   / "index.html",
    ),
    (
        WEB_SRC_DIR / "ota.html",
        INCLUDE_DIR / "web_interface_ota.h",
        "OTA_PAGE",
        None,
    ),
    (
        WEB_SRC_DIR / "scan.html",
        INCLUDE_DIR / "web_interface_scan.h",
        "SCAN_PAGE",
        None,
    ),
]

# ---------------------------------------------------------------------------
# Optional minifiers (graceful fallback)
# ---------------------------------------------------------------------------
try:
    import rcssmin
    HAS_RCSSMIN = True
except ImportError:
    HAS_RCSSMIN = False

try:
    import rjsmin
    HAS_RJSMIN = True
except ImportError:
    HAS_RJSMIN = False

# ---------------------------------------------------------------------------
# HTML minification helpers
# ---------------------------------------------------------------------------
def _minify_css_block(css: str) -> str:
    if HAS_RCSSMIN:
        return rcssmin.cssmin(css)
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.DOTALL)
    css = re.sub(r'\s*([{}:;,>~+])\s*', r'\1', css)
    css = re.sub(r'\s+', ' ', css).strip()
    return css


def _minify_js_block(js: str) -> str:
    if HAS_RJSMIN:
        return rjsmin.jsmin(js)
    js = re.sub(r'//[^\n]*', '', js)
    js = re.sub(r'\s+', ' ', js).strip()
    return js


def minify_html(html: str) -> str:
    html = re.sub(r'<!--(?!\[if).*?-->', '', html, flags=re.DOTALL)
    def _repl_style(m):
        return '<style>' + _minify_css_block(m.group(1)) + '</style>'
    html = re.sub(r'<style>(.*?)</style>', _repl_style, html, flags=re.DOTALL)
    def _repl_script(m):
        return '<script>' + _minify_js_block(m.group(1)) + '</script>'
    html = re.sub(r'<script>(.*?)</script>', _repl_script, html, flags=re.DOTALL)
    html = re.sub(r'>\s+<', '><', html)
    html = re.sub(r'[ \t]{2,}', ' ', html)
    html = re.sub(r'\n\s*\n', '\n', html)
    return html.strip()


# ---------------------------------------------------------------------------
# HTML header generation
# ---------------------------------------------------------------------------
HTML_HEADER_TEMPLATE = """\
// Auto-generated by tools/minify_web.py — NE PAS MODIFIER MANUELLEMENT
// Source : {src}
#pragma once

static const char {const_name}[] PROGMEM = R"HTML(
{html}
)HTML";
"""


def generate_html_header(src_path: Path, const_name: str, minified_html: str) -> str:
    return HTML_HEADER_TEMPLATE.format(
        src=src_path.relative_to(PROJECT_ROOT),
        const_name=const_name,
        html=minified_html,
    )


# ---------------------------------------------------------------------------
# OUI table generation
# Lit data/oui.json et génère include/oui_table.h avec OUI_TABLE[]
# ---------------------------------------------------------------------------
OUI_HEADER_TEMPLATE = """\
// Auto-generated by tools/minify_web.py — NE PAS MODIFIER MANUELLEMENT
// Source : {src}
// {count} entrées OUI
#pragma once

struct OuiEntry {{
    const char* oui;
    const char* manufacturer;
    const char* category;
}};

static const OuiEntry OUI_TABLE[] = {{
{entries}
}};
"""


def generate_oui_header(src_path: Path, entries: list) -> str:
    seen = set()
    lines = []
    for e in entries:
        oui = e["oui"].upper()
        if oui in seen:
            continue
        seen.add(oui)
        mfr = e["manufacturer"].replace('"', '\\"')
        cat = e["category"].replace('"', '\\"')
        lines.append(f'    {{"{oui}", "{mfr}", "{cat}"}},')
    return OUI_HEADER_TEMPLATE.format(
        src=src_path.relative_to(PROJECT_ROOT),
        count=len(lines),
        entries="\n".join(lines),
    )


def process_oui(ok: bool) -> bool:
    src = DATA_DIR / "oui.json"
    dst = INCLUDE_DIR / "oui_table.h"

    if not src.exists():
        print(f"  ERREUR : {src.relative_to(PROJECT_ROOT)} introuvable — ignoré")
        return False

    raw = src.read_text(encoding='utf-8')
    entries = json.loads(raw)
    minified_json = json.dumps(entries, separators=(',', ':'), ensure_ascii=False)
    ratio = 100 * (1 - len(minified_json) / len(raw))

    header = generate_oui_header(src, entries)
    dst.write_text(header, encoding='utf-8')

    print(f"\n  [oui.json]")
    print(f"    Entrées : {len(entries)} ({len(set(e['oui'].upper() for e in entries))} uniques)")
    print(f"    Source  : {len(raw):,} octets")
    print(f"    Minifié : {len(minified_json):,} octets  (gain {ratio:.1f}%)")
    print(f"    Header  : {dst.relative_to(PROJECT_ROOT)}")
    return ok


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def run():
    print("=" * 55)
    print("Gateway Lab V1 — Minification assets")
    print("=" * 55)

    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    ok = True

    # --- Pages HTML ---
    for src, header_dst, const_name, data_dst in PAGES:
        if not src.exists():
            print(f"  ERREUR : {src.relative_to(PROJECT_ROOT)} introuvable — ignoré")
            ok = False
            continue

        raw = src.read_text(encoding='utf-8')
        minified = minify_html(raw)
        ratio = 100 * (1 - len(minified) / len(raw))

        header = generate_html_header(src, const_name, minified)
        header_dst.write_text(header, encoding='utf-8')

        print(f"\n  [{src.name}]")
        print(f"    Source  : {len(raw):,} octets")
        print(f"    Minifié : {len(minified):,} octets  (gain {ratio:.1f}%)")
        print(f"    Header  : {header_dst.relative_to(PROJECT_ROOT)}")

        if data_dst is not None:
            data_dst.write_text(minified, encoding='utf-8')
            print(f"    Data    : {data_dst.relative_to(PROJECT_ROOT)}")

    # --- Table OUI ---
    ok = process_oui(ok)

    print("\nOK\n" if ok else "\nTerminé avec des erreurs\n")
    return ok


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    sys.exit(0 if run() else 1)
