#!/usr/bin/env python3
"""
Web Assets Minifier — Gateway Lab V1

Minifie les sources HTML et génère les headers C++ PROGMEM :
  - web_src/index.html  →  include/web_interface.h     (INDEX_HTML)
  - web_src/ota.html    →  include/web_interface_ota.h (OTA_PAGE)
  - data/index.html         (copie minifiée, optionnelle)

Peut être exécuté en standalone ou comme pre-script PlatformIO.

Usage standalone :
    python tools/minify_web.py

PlatformIO (extra_scripts = pre:tools/minify_web.py) :
    Exécuté automatiquement avant chaque compilation.

Requirements (optionnels — fallback intégré) :
    pip install rcssmin rjsmin
"""

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Résolution du chemin racine du projet
#
# En mode PlatformIO (SCons), __file__ n'est pas défini.
# On utilise env.GetProjectDir() fourni par SCons.
# En mode standalone (python tools/minify_web.py), on utilise __file__.
# ---------------------------------------------------------------------------
try:
    Import("env")                           # type: ignore  # noqa: F821
    _IS_PLATFORMIO = True
    PROJECT_ROOT = Path(env.GetProjectDir())  # type: ignore  # noqa: F821
except NameError:
    _IS_PLATFORMIO = False
    PROJECT_ROOT = Path(__file__).resolve().parent.parent

WEB_SRC_DIR = PROJECT_ROOT / "web_src"
DATA_DIR    = PROJECT_ROOT / "data"
INCLUDE_DIR = PROJECT_ROOT / "include"

# ---------------------------------------------------------------------------
# Pages à traiter : (source, header_dest, const_name)
# ---------------------------------------------------------------------------
PAGES = [
    (
        WEB_SRC_DIR / "index.html",
        INCLUDE_DIR / "web_interface.h",
        "INDEX_HTML",
        DATA_DIR   / "index.html",   # copie data/ (None pour désactiver)
    ),
    (
        WEB_SRC_DIR / "ota.html",
        INCLUDE_DIR / "web_interface_ota.h",
        "OTA_PAGE",
        None,
    ),
]

# ---------------------------------------------------------------------------
# Optional minifiers (graceful fallback)
# ---------------------------------------------------------------------------
try:
    import rcssmin
    HAS_RCSSMIN = True
except ImportError:
    HAS_RCSSMIN = False

try:
    import rjsmin
    HAS_RJSMIN = True
except ImportError:
    HAS_RJSMIN = False

# ---------------------------------------------------------------------------
# Minification helpers
# ---------------------------------------------------------------------------
def _minify_css_block(css: str) -> str:
    if HAS_RCSSMIN:
        return rcssmin.cssmin(css)
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.DOTALL)
    css = re.sub(r'\s*([{}:;,>~+])\s*', r'\1', css)
    css = re.sub(r'\s+', ' ', css).strip()
    return css


def _minify_js_block(js: str) -> str:
    if HAS_RJSMIN:
        return rjsmin.jsmin(js)
    js = re.sub(r'//[^\n]*', '', js)
    js = re.sub(r'\s+', ' ', js).strip()
    return js


def minify_html(html: str) -> str:
    html = re.sub(r'<!--(?!\[if).*?-->', '', html, flags=re.DOTALL)
    def _repl_style(m):
        return '<style>' + _minify_css_block(m.group(1)) + '</style>'
    html = re.sub(r'<style>(.*?)</style>', _repl_style, html, flags=re.DOTALL)
    def _repl_script(m):
        return '<script>' + _minify_js_block(m.group(1)) + '</script>'
    html = re.sub(r'<script>(.*?)</script>', _repl_script, html, flags=re.DOTALL)
    html = re.sub(r'>\s+<', '><', html)
    html = re.sub(r'[ \t]{2,}', ' ', html)
    html = re.sub(r'\n\s*\n', '\n', html)
    return html.strip()


# ---------------------------------------------------------------------------
# Header generation
# ---------------------------------------------------------------------------
HEADER_TEMPLATE = """\
// Auto-generated by tools/minify_web.py — NE PAS MODIFIER MANUELLEMENT
// Source : {src}
#pragma once

static const char {const_name}[] PROGMEM = R"HTML(
{html}
)HTML";
"""


def generate_header(src_path: Path, const_name: str, minified_html: str) -> str:
    return HEADER_TEMPLATE.format(
        src=src_path.relative_to(PROJECT_ROOT),
        const_name=const_name,
        html=minified_html,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def run():
    print("=" * 55)
    print("Gateway Lab V1 — Minification HTML")
    print("=" * 55)

    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    ok = True
    for src, header_dst, const_name, data_dst in PAGES:
        if not src.exists():
            print(f"  ERREUR : {src.relative_to(PROJECT_ROOT)} introuvable — ignoré")
            ok = False
            continue

        raw = src.read_text(encoding='utf-8')
        minified = minify_html(raw)
        ratio = 100 * (1 - len(minified) / len(raw))

        header = generate_header(src, const_name, minified)
        header_dst.write_text(header, encoding='utf-8')

        print(f"\n  [{src.name}]")
        print(f"    Source  : {len(raw):,} octets")
        print(f"    Minifié : {len(minified):,} octets  (gain {ratio:.1f}%)")
        print(f"    Header  : {header_dst.relative_to(PROJECT_ROOT)}")

        if data_dst is not None:
            data_dst.write_text(minified, encoding='utf-8')
            print(f"    Data    : {data_dst.relative_to(PROJECT_ROOT)}")

    print("\nOK\n" if ok else "\nTerminé avec des erreurs\n")
    return ok


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------
if _IS_PLATFORMIO:
    run()
elif __name__ == "__main__":
    sys.exit(0 if run() else 1)
